### ISSUE TITLE
[chartink to tradingview

### ISSUE THREAD

**Issue by ravishahane** [devAgam/chartink-to-tradingview-firefox-extension#1]
Hi 

I have been using your Chrome extension, [chartink to tradingview], for some time now and have found it to be incredibly useful. I appreciate the time and effort you have put into creating this tool, and it has been a valuable addition to my work.

I am now hoping to extend the use of this extension to another website, [https://zone.definedgesecurities.com/], but am unsure how to do so. I was wondering if you could provide some guidance or instructions on how to integrate your extension with this particular website.

**Comment by devAgam** [comment]
Hey Ravi, Glad to know you found the extension helpful. Still, to allow me to integrate the extension with the said website, it would require me to create a proper account with them, which I'm not willing to do because it requires uploading my personal and government IDs.

Feel free to fork the repo and maintain your own version for the said website; from what I belive, the code should be primarily cross-compatible with other similar sites.

**Comment by ravishahane** [comment]
You can create account this website without using government ID 
https://tradepoint.definedge.com/index.html#chart

**Comment by devAgam** [comment]
That just shows me a chart; where do you expect the redirect to occur?
![Screenshot 2023-03-18 at 2 21 33 PM](https://user-images.githubusercontent.com/46868711/226095569-cbf6aad1-af98-4cc6-a304-12f6437e0a4d.png)

**Comment by ravishahane** [comment]
right side  above click on RZONE

**Comment by devAgam** [comment]
Needs a paid plan to access.

![Screenshot 2023-03-18 at 2 45 10 PM](https://user-images.githubusercontent.com/46868711/226096653-57547a70-bbc5-46f7-a656-7b8b26972fb4.png)

**Comment by ravishahane** [comment]
1 month trial free

**Comment by devAgam** [comment]
Link ?

**Comment by ravishahane** [comment]
I think they sent promo code email

**Comment by devAgam** [comment]
I Sadly Have not received any emails like this, I will work on this if I get the email.

**Comment by ravishahane** [comment]
Are you Indian

**Comment by devAgam** [comment]
Yes

**Comment by ravishahane** [comment]
Why not open account definedgesecurities you get one month he trial instant

**Comment by devAgam** [comment]
I neither use the service nor have any interest in it.

**Comment by ravishahane** [comment]
You not trade Indian markets

**Comment by devAgam** [comment]
I do trade Indian Markets

**Comment by ravishahane** [comment]
> Needs a paid plan to access.
> 
> ![Screenshot 2023-03-18 at 2 45 10 PM](https://user-images.githubusercontent.com/46868711/226096653-57547a70-bbc5-46f7-a656-7b8b26972fb4.png)

HI I PAID 1 MONTH CAN YOU DO THAT
